export const ORDER_STATUS = {
  RECEIVED: 'RECEIVED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
}

export const STATUS_TRANSITIONS = {
  [ORDER_STATUS.RECEIVED]: ORDER_STATUS.IN_PROGRESS,
  [ORDER_STATUS.IN_PROGRESS]: ORDER_STATUS.COMPLETED,
}
